baseURL = "https://blog.gocache.top/"
languageCode = "zh-cn"
title = "价格行为"
theme = "echo"
DefaultContentLanguage = "cn"
hasCJKLanguage = true
uglyURLs = true

[permalinks]
posts = "/:filename"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[services.rss]
limit = 20

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 2

[author]
name = "Dongbin"
bio = "记录技术与生活"

[params]
htmlClass = "dark"
toc = true
rssFullContent = true
uglyURLs = true
navItems = [
  ["首页", "/"],
  ["文章归档", "/posts.html"],
  ["标签", "/tags.html"],
  ["关于我", "/about.html"]
]

[params.cc]
name = "署名 - 非商业性使用 4.0 国际 (CC BY-NC 4.0)"
link = "https://creativecommons.org/licenses/by-nc/4.0/deed.zh"

[social]
github = "dongbin"
rss = "/atom.xml"
